class Comment {
  final double id;
  final String content;
  final String createdAt;
  final String updatedAt;
  final String userId;
  final String userProfileImage;
  final String nickName;

  Comment({
    required this.id,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
    required this.userId,
    required this.userProfileImage,
    required this.nickName,
  });

  static List<Comment> testComment = [
    Comment(
      id: 1,
      content:
          'ㅁㄴㅇ뤠붐ㄴ라ㅓㅁㄴ이ㅜ핀ㅁ챌ㅇㄹㄴㄹㄴㅇ머ㅣㅜㅍㅋㅌ치풔ㅏ룾버ㅜㄹㅁ느,풏ㅌㅋ퍼ㅗ머ㅑ로ㅜㄴㅇ미 ㄹ ㄴㅇ미러채ㅑㅍㅁㅌㅊ런ㅇ메ㅐㅁㄹㄴㅇ물ㄴ뭉ㄴㅁㄹ야냄렁ㄴ뭍ㅊㅋ피;ㅊㅌㅋ펀야ㅐㄹㅇ너리무내ㅔㅍ모처물ㅇ네ㅐㅁㄹㄴ오ㅓㄹ',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 1,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-11',
      updatedAt: '2024-09-09',
      userId: '1',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
    Comment(
      id: 2,
      content: 'fksldjflasjfdoasjflasfndlsfjdslofjdsafjasdf',
      createdAt: '2024-09-12',
      updatedAt: '2024-09-09',
      userId: 'x',
      userProfileImage: '',
      nickName: 'vitabin',
    ),
  ];
}
